# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./cmd/picoclaw

builds:
  - id: picoclaw
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - riscv64
      - s390x
      - mips64
      - arm
    main: ./cmd/picoclaw
    ignore:
      - goos: windows
        goarch: arm

  # Android/Termux requires PIE executables (ET_DYN) built with GOOS=android.
  # Standard Linux binaries (ET_EXEC) are rejected by Android's kernel.
  - id: picoclaw-android
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - android
    goarch:
      - arm64
    main: ./cmd/picoclaw

dockers_v2:
  - id: picoclaw
    dockerfile: Dockerfile.goreleaser
    ids:
      - picoclaw
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/picoclaw"
      - "docker.io/{{ .Env.DOCKERHUB_IMAGE_NAME }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/riscv64

archives:
  - ids:
      - picoclaw
      - picoclaw-android
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# upx:
#    - enabled: true
#      compress: best
#      lzma: true

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
