// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGatewayStatus() {
  return window['go']['main']['App']['GetGatewayStatus']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetSetupStatus() {
  return window['go']['main']['App']['GetSetupStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSetup(arg1) {
  return window['go']['main']['App']['SaveSetup'](arg1);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function TestLLM(arg1) {
  return window['go']['main']['App']['TestLLM'](arg1);
}
