// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<Record<string, any>>;

export function GetGatewayStatus():Promise<main.GatewayStatus>;

export function GetLogs(arg1:number):Promise<Record<string, any>>;

export function GetSetupStatus():Promise<main.SetupStatusResult>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveSetup(arg1:main.TestLLMRequest):Promise<main.SaveSetupResult>;

export function SendChat(arg1:string):Promise<main.ChatResult>;

export function StartGateway():Promise<string>;

export function StopGateway():Promise<string>;

export function TestLLM(arg1:main.TestLLMRequest):Promise<main.TestLLMResult>;
