// genbuild reads build.yaml (channels.include) and
// generates cmd/picoclaw/internal/gateway/channels_imports.go so only the
// selected channels are compiled in, reducing binary size.
//
// Run before build: go run ./scripts/genbuild
// Or use: make build (which runs this via the generate target).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	buildConfigName = "build.yaml"
	outputPath      = "cmd/picoclaw/internal/gateway/channels_imports.go"
	modulePath      = "github.com/sipeed/picoclaw"
)

type buildConfig struct {
	// Preferred allowlist model:
	//   channels:
	//     include: [telegram, whatsapp]
	// Optional denylist model:
	//   channels:
	//     skip: [telegram, whatsapp]
	Channels struct {
		Include []string `yaml:"include"`
		Skip    []string `yaml:"skip"`
	} `yaml:"channels"`
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genbuild: %v\n", err)
		os.Exit(1)
	}

	cfg := loadConfig(repoRoot)

	allChannels, err := discoverChannels(repoRoot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genbuild: discover channels: %v\n", err)
		os.Exit(1)
	}

	include := selectChannels(allChannels, cfg)

	outPath := filepath.Join(repoRoot, outputPath)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genbuild: %v\n", err)
		os.Exit(1)
	}

	content := generateImports(include)
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genbuild: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "genbuild: wrote %s (%d channels)\n", outputPath, len(include))
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found (run from repo root)")
		}
		dir = parent
	}
}

func loadConfig(repoRoot string) *buildConfig {
	cfg := &buildConfig{}
	path := filepath.Join(repoRoot, buildConfigName)
	data, err := os.ReadFile(path)
	if err != nil {
		// No build.yaml: include all channels
		return cfg
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		fmt.Fprintf(os.Stderr, "genbuild: warning: %s: %v (including all channels)\n", path, err)
		return cfg
	}
	return cfg
}

// discoverChannels returns all channel package names (directory names under pkg/channels/).
func discoverChannels(repoRoot string) ([]string, error) {
	dir := filepath.Join(repoRoot, "pkg", "channels")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var channels []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
			continue
		}
		channels = append(channels, name)
	}

	sort.Strings(channels)
	return channels, nil
}

// selectChannels applies the config to the discovered channels, preferring the
// allowlist model (channels.include), and optionally the denylist model (channels.skip).
func selectChannels(all []string, cfg *buildConfig) []string {
	if len(all) == 0 {
		return nil
	}

	available := make(map[string]struct{}, len(all))
	for _, ch := range all {
		available[ch] = struct{}{}
	}

	// 1) Preferred allowlist: channels.include
	if len(cfg.Channels.Include) > 0 {
		var include []string
		for _, raw := range cfg.Channels.Include {
			name := strings.TrimSpace(raw)
			if name == "" {
				continue
			}
			if _, ok := available[name]; !ok {
				fmt.Fprintf(os.Stderr, "genbuild: warning: channel %q listed in channels.include but no such pkg/channels/%s\n", name, name)
				continue
			}
			include = append(include, name)
		}
		if len(include) == 0 {
			// Nothing matched; fall back to "all" to avoid surprising empty builds.
			return all
		}
		sort.Strings(include)
		return include
	}

	// 2) denylist: channels.skip.
	skipSet := make(map[string]struct{})
	for _, raw := range cfg.Channels.Skip {
		name := strings.TrimSpace(raw)
		if name == "" {
			continue
		}
		skipSet[name] = struct{}{}
	}

	if len(skipSet) == 0 {
		// No config at all or no skip entries: include all channels.
		return all
	}

	var include []string
	for _, ch := range all {
		if _, skip := skipSet[ch]; skip {
			continue
		}
		include = append(include, ch)
	}
	return include
}

func generateImports(channels []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/genbuild. DO NOT EDIT.\n")
	b.WriteString("// Edit build.yaml and run: go run ./scripts/genbuild (or make build).\n\n")
	b.WriteString("package gateway\n\n")
	b.WriteString("import (\n")
	for _, ch := range channels {
		b.WriteString("\t_ \"")
		b.WriteString(modulePath)
		b.WriteString("/pkg/channels/")
		b.WriteString(ch)
		b.WriteString("\"\n")
	}
	b.WriteString(")\n")
	return b.String()
}
