/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchTaskIdRouteImport } from './routes/research/$taskId'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchTaskIdRoute = ResearchTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ResearchRoute,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRouteWithChildren
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/research/$taskId': typeof ResearchTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRouteWithChildren
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/research/$taskId': typeof ResearchTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRouteWithChildren
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/research/$taskId': typeof ResearchTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/research'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/research/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/research'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/research/$taskId'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/research'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/research/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  ResearchRoute: typeof ResearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$taskId': {
      id: '/research/$taskId'
      path: '/$taskId'
      fullPath: '/research/$taskId'
      preLoaderRoute: typeof ResearchTaskIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface ResearchRouteChildren {
  ResearchTaskIdRoute: typeof ResearchTaskIdRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchTaskIdRoute: ResearchTaskIdRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  ResearchRoute: ResearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
