name: PR

on:
  pull_request: {}

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Run go generate
        run: go generate ./...

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Run go generate
        run: go generate ./...

      - name: Run frontend tests
        run: |
          pnpm --dir pkg/miniapp/frontend install --frozen-lockfile
          pnpm --dir pkg/miniapp/frontend test

      - name: Run go test
        run: go test ./...
