// PicoClaw - Ultra-lightweight personal AI agent
// License: MIT
//
// Copyright (c) 2026 PicoClaw contributors

package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/sipeed/picoclaw/pkg/logger"
	"github.com/sipeed/picoclaw/pkg/providers"
)

// AnalyseResult holds the output of the Phase 1 (Analyse) step.
type AnalyseResult struct {
	// Intent is a short label classifying the user's intent (e.g. "question", "task", "chat").
	Intent string `json:"intent"`
	// Tags extracted from the user message for memory retrieval.
	Tags []string `json:"tags"`
	// CotPrompt is an LLM-generated thinking strategy tailored to the user's message.
	// Generated by the analyser, not selected from a fixed list.
	CotPrompt string `json:"cot_prompt"`
	// MemoryContext is the formatted memory entries matching the extracted tags.
	// This is populated after the memory lookup, not by the LLM itself.
	MemoryContext string `json:"-"`
}



// Analyser performs a lightweight LLM call to analyse the user's message,
// extract intent and tags, then queries the memory store for relevant entries.
// This is Phase 1 of the Runtime Loop.
//
// Flow:
//  1. Collect all available tags from the memory store.
//  2. Call a small/fast LLM with the user message + available tags.
//  3. Parse the JSON response to get intent + matched tags.
//  4. Query memory entries by those tags.
//  5. Return the result with formatted memory context.
type Analyser struct {
	provider    providers.LLMProvider
	model       string
	cotRegistry *CotRegistry
}



// NewAnalyser creates a new Analyser (Phase 1) processor.
// model should be a lightweight model identifier like "gemini/gemini-2.0-flash-exp".
func NewAnalyser(provider providers.LLMProvider, model string, cotRegistry *CotRegistry) *Analyser {
	return &Analyser{
		provider:    provider,
		model:       model,
		cotRegistry: cotRegistry,
	}
}



const preLLMSystemPromptTpl = `You are a message analysis engine. Your job is to analyse the user's message and output a JSON object.

## Task

Given the user message, a list of available memory tags, and reference thinking strategy examples, you must:
1. Determine the user's **intent** — classify it into one short label.
2. Select **relevant tags** from the available tag list. Only select genuinely relevant tags. 0 tags if none are relevant.
3. **Generate a custom thinking strategy** (cot_prompt) for the main AI to follow when processing this message. This should be a concise, actionable set of steps tailored to the specific task.

## Output Format

Respond with ONLY a valid JSON object, no markdown fences, no explanation:

{"intent":"<intent_label>","tags":["<tag1>"],"cot_prompt":"<thinking_strategy_text>"}

The cot_prompt should be a brief strategy (3-6 numbered steps). For simple chat/greetings, use an empty string "".

## Intent Labels

Use one of: question, task, chat, code, search, create, debug, explain, translate, summarise, other

## Reference Thinking Strategy Examples

Use these as inspiration — adapt and combine as needed for the specific message:

%s

%s

## Rules

- ONLY select tags from the provided available tags list.
- Do NOT invent new tags. Only use tags from the available list.
- Maximum 5 tags.
- Generate a cot_prompt tailored to the specific user message. Don't just copy examples — adapt them.
- For simple chat (greetings, thanks, etc.), use an empty cot_prompt.
- If historical data shows which strategies worked well for similar intents, prefer those approaches.
- Keep the cot_prompt concise: 3-6 actionable steps.
- Keep it fast — this is a preprocessing step.`

// Analyse runs the pre-LLM analysis on the user message.
// It returns an AnalyseResult with intent, tags, and formatted memory context.
// If the pre-LLM call fails, it returns a zero-value result (no error propagation
// to avoid blocking the main agent loop).
// actCtx may be nil; when provided, its content is injected into the user prompt
// (not the system prompt) to preserve system prompt prefix stability for KV cache.
func (p *Analyser) Analyse(ctx context.Context, userMessage string, memory *MemoryStore, actCtx *ActiveContext) AnalyseResult {
	if p.provider == nil || p.model == "" {
		return AnalyseResult{}
	}

	start := time.Now()

	// 1. Collect available tags from memory store.
	var availableTags []string
	var tagsErr error
	if memory != nil {
		availableTags, tagsErr = memory.ListAllTags()
	}
	hasMemoryTags := tagsErr == nil && len(availableTags) > 0

	// Even without memory tags, we still call pre-LLM for CoT selection.

	// 2. Build the system prompt with example templates + learning history.
	examples := ""
	if p.cotRegistry != nil {
		examples = p.cotRegistry.ListExamplesForPrompt()
	}
	// Include historical CoT performance data + top-rated prompts for learning.
	cotHistory := ""
	if memory != nil {
		// Pass available tags so proven examples can be filtered by relevance.
		cotHistory = memory.FormatCotLearningContext(30, availableTags)
	}
	systemPrompt := fmt.Sprintf(preLLMSystemPromptTpl, examples, cotHistory)

	// 3. Build the user prompt with available tags + active context.
	var userPromptBuilder strings.Builder

	// Active Context block (injected here to keep system prompt prefix stable).
	if actCtx != nil {
		if ac := actCtx.Format(); ac != "" {
			userPromptBuilder.WriteString(ac)
			userPromptBuilder.WriteString("\n\n")
		}
	}

	if hasMemoryTags {
		fmt.Fprintf(&userPromptBuilder, "Available tags: [%s]\n\nUser message: %s",
			strings.Join(availableTags, ", "), userMessage)
	} else {
		fmt.Fprintf(&userPromptBuilder, "Available tags: [](none)\n\nUser message: %s", userMessage)
	}
	userPrompt := userPromptBuilder.String()

	messages := []providers.Message{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: userPrompt},
	}

	// 4. Call the LLM (no tools, moderate max_tokens for generated CoT, low temperature).
	resp, err := p.provider.Chat(ctx, messages, nil, p.model, map[string]any{
		"max_tokens":  512,
		"temperature": 0.3,
	})
	if err != nil {
		logger.WarnCF("analyser", "Pre-LLM call failed, proceeding without enrichment",
			map[string]any{"error": err.Error(), "model": p.model})
		return AnalyseResult{}
	}

	// 5. Parse the JSON response.
	result := p.parseResponse(resp.Content)

	// 6. Query memory by extracted tags.
	if len(result.Tags) > 0 && memory != nil {
		entries, err := memory.SearchByAnyTag(result.Tags)
		if err == nil && len(entries) > 0 {
			result.MemoryContext = formatMemoryEntries(entries)
		}
	}

	// 7. Record usage for learning (non-blocking — don't fail the main flow).
	if memory != nil && result.CotPrompt != "" {
		if _, err := memory.RecordCotUsage(result.Intent, result.Tags, result.CotPrompt, userMessage); err != nil {
			logger.DebugCF("analyser", "Failed to record CoT usage",
				map[string]any{"error": err.Error()})
		}
	}

	elapsed := time.Since(start)
	logger.InfoCF("analyser", "Pre-LLM analysis complete",
		map[string]any{
			"intent":          result.Intent,
			"tags":            result.Tags,
			"has_cot":         result.CotPrompt != "",
			"cot_len":         len(result.CotPrompt),
			"memory_entries":  countMemoryLines(result.MemoryContext),
			"elapsed_ms":      elapsed.Milliseconds(),
			"model":           p.model,
			"available_tags":  len(availableTags),
		})

	return result
}

// parseResponse extracts intent and tags from the LLM's JSON response.
// Handles common LLM quirks like markdown fences around JSON.
func (p *Analyser) parseResponse(content string) AnalyseResult {
	content = strings.TrimSpace(content)

	// Strip markdown code fences if present.
	if strings.HasPrefix(content, "```") {
		lines := strings.Split(content, "\n")
		// Remove first and last lines (fences).
		if len(lines) >= 3 {
			content = strings.Join(lines[1:len(lines)-1], "\n")
		}
	}
	content = strings.TrimSpace(content)

	var result AnalyseResult
	if err := json.Unmarshal([]byte(content), &result); err != nil {
		logger.WarnCF("analyser", "Failed to parse pre-LLM response as JSON",
			map[string]any{
				"error":   err.Error(),
				"content": content,
			})
		return AnalyseResult{}
	}

	// Sanitise: lowercase tags, limit to 5.
	cleaned := make([]string, 0, len(result.Tags))
	for _, t := range result.Tags {
		t = strings.ToLower(strings.TrimSpace(t))
		if t != "" {
			cleaned = append(cleaned, t)
		}
	}
	if len(cleaned) > 5 {
		cleaned = cleaned[:5]
	}
	result.Tags = cleaned

	return result
}

// formatMemoryEntries formats memory entries into a string for injection into context.
func formatMemoryEntries(entries []MemoryEntry) string {
	if len(entries) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("## Relevant Memories (auto-retrieved)\n\n")
	for _, e := range entries {
		tagLabel := ""
		if len(e.Tags) > 0 {
			tagLabel = " [" + strings.Join(e.Tags, ", ") + "]"
		}
		fmt.Fprintf(&sb, "- (#%d%s) %s\n", e.ID, tagLabel, e.Content)
	}
	return sb.String()
}

// countMemoryLines counts the number of memory entries in a formatted string.
func countMemoryLines(s string) int {
	if s == "" {
		return 0
	}
	count := 0
	for _, line := range strings.Split(s, "\n") {
		if strings.HasPrefix(line, "- (#") {
			count++
		}
	}
	return count
}
