package agent

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sync"
	"time"
)

// Artifact represents a trackable product generated by the LLM
// such as code, images, documents, or data files.
type Artifact struct {
	ID           string         `json:"id"`                 // Unique identifier
	Type         ArtifactType   `json:"type"`               // Type of artifact
	Content      string         `json:"content"`            // Artifact content
	MIME         string         `json:"mime"`               // MIME type if applicable
	Size         int64          `json:"size"`               // Size in bytes
	Created      time.Time      `json:"created"`            // Creation timestamp
	SessionID    string         `json:"session_id"`         // Associated session
	MessageIndex int            `json:"message_index"`      // Index in message history
	Metadata     map[string]any `json:"metadata,omitempty"` // Additional metadata

	// Optional fields for enhanced tracking
	Language    string `json:"language,omitempty"`    // Programming language (for code)
	Filename    string `json:"filename,omitempty"`    // Suggested filename
	Description string `json:"description,omitempty"` // Human-readable description
}

// ArtifactManager manages the lifecycle of artifacts within agent sessions
type ArtifactManager struct {
	mu        sync.RWMutex
	artifacts map[string]*Artifact // ID -> Artifact
	bySession map[string][]string  // SessionID -> []ArtifactID
}

// NewArtifactManager creates a new artifact manager
func NewArtifactManager() *ArtifactManager {
	return &ArtifactManager{
		artifacts: make(map[string]*Artifact),
		bySession: make(map[string][]string),
	}
}

// CreateArtifact creates and registers a new artifact
func (am *ArtifactManager) CreateArtifact(artifactType ArtifactType, content, sessionID string) *Artifact {
	artifact := &Artifact{
		ID:        generateArtifactID(content),
		Type:      artifactType,
		Content:   content,
		Size:      int64(len(content)),
		Created:   time.Now(),
		SessionID: sessionID,
		Metadata:  make(map[string]any),
	}

	am.mu.Lock()
	defer am.mu.Unlock()

	am.artifacts[artifact.ID] = artifact
	am.bySession[sessionID] = append(am.bySession[sessionID], artifact.ID)

	return artifact
}

// AddArtifact registers an existing artifact
func (am *ArtifactManager) AddArtifact(artifact *Artifact) {
	am.mu.Lock()
	defer am.mu.Unlock()

	if artifact.ID == "" {
		artifact.ID = generateArtifactID(artifact.Content)
	}

	am.artifacts[artifact.ID] = artifact
	am.bySession[artifact.SessionID] = append(am.bySession[artifact.SessionID], artifact.ID)
}

// GetArtifact retrieves an artifact by ID
func (am *ArtifactManager) GetArtifact(id string) (*Artifact, bool) {
	am.mu.RLock()
	defer am.mu.RUnlock()

	artifact, ok := am.artifacts[id]
	return artifact, ok
}

// GetSessionArtifacts retrieves all artifacts for a session
func (am *ArtifactManager) GetSessionArtifacts(sessionID string) []*Artifact {
	am.mu.RLock()
	defer am.mu.RUnlock()

	ids, ok := am.bySession[sessionID]
	if !ok {
		return nil
	}

	artifacts := make([]*Artifact, 0, len(ids))
	for _, id := range ids {
		if artifact, ok := am.artifacts[id]; ok {
			artifacts = append(artifacts, artifact)
		}
	}

	return artifacts
}

// GetRecentArtifacts retrieves the N most recent artifacts for a session
func (am *ArtifactManager) GetRecentArtifacts(sessionID string, limit int) []*Artifact {
	artifacts := am.GetSessionArtifacts(sessionID)

	if len(artifacts) <= limit {
		return artifacts
	}

	// Return the last N artifacts
	return artifacts[len(artifacts)-limit:]
}

// GetArtifactsByType retrieves all artifacts of a specific type in a session
func (am *ArtifactManager) GetArtifactsByType(sessionID string, artifactType ArtifactType) []*Artifact {
	am.mu.RLock()
	defer am.mu.RUnlock()

	ids, ok := am.bySession[sessionID]
	if !ok {
		return nil
	}

	var result []*Artifact
	for _, id := range ids {
		if artifact, ok := am.artifacts[id]; ok && artifact.Type == artifactType {
			result = append(result, artifact)
		}
	}

	return result
}

// UpdateArtifact updates an existing artifact
func (am *ArtifactManager) UpdateArtifact(id string, updateFn func(*Artifact)) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	artifact, ok := am.artifacts[id]
	if !ok {
		return fmt.Errorf("artifact not found: %s", id)
	}

	updateFn(artifact)
	return nil
}

// DeleteArtifact removes an artifact
func (am *ArtifactManager) DeleteArtifact(id string) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	artifact, ok := am.artifacts[id]
	if !ok {
		return fmt.Errorf("artifact not found: %s", id)
	}

	// Remove from artifacts map
	delete(am.artifacts, id)

	// Remove from session index
	if ids, ok := am.bySession[artifact.SessionID]; ok {
		newIds := make([]string, 0, len(ids)-1)
		for _, artifactID := range ids {
			if artifactID != id {
				newIds = append(newIds, artifactID)
			}
		}
		am.bySession[artifact.SessionID] = newIds
	}

	return nil
}

// DeleteSessionArtifacts removes all artifacts for a session
func (am *ArtifactManager) DeleteSessionArtifacts(sessionID string) int {
	am.mu.Lock()
	defer am.mu.Unlock()

	ids, ok := am.bySession[sessionID]
	if !ok {
		return 0
	}

	count := 0
	for _, id := range ids {
		delete(am.artifacts, id)
		count++
	}

	delete(am.bySession, sessionID)
	return count
}

// CountArtifacts returns the total number of artifacts
func (am *ArtifactManager) CountArtifacts() int {
	am.mu.RLock()
	defer am.mu.RUnlock()
	return len(am.artifacts)
}

// CountSessionArtifacts returns the number of artifacts in a session
func (am *ArtifactManager) CountSessionArtifacts(sessionID string) int {
	am.mu.RLock()
	defer am.mu.RUnlock()
	return len(am.bySession[sessionID])
}

// GetStats returns statistics about artifacts
func (am *ArtifactManager) GetStats() ArtifactStats {
	am.mu.RLock()
	defer am.mu.RUnlock()

	stats := ArtifactStats{
		Total:     len(am.artifacts),
		ByType:    make(map[ArtifactType]int),
		BySession: make(map[string]int),
	}

	for _, artifact := range am.artifacts {
		stats.ByType[artifact.Type]++
		stats.TotalSize += artifact.Size
	}

	for sessionID, ids := range am.bySession {
		stats.BySession[sessionID] = len(ids)
	}

	return stats
}

// ArtifactStats provides statistics about artifacts
type ArtifactStats struct {
	Total     int
	TotalSize int64
	ByType    map[ArtifactType]int
	BySession map[string]int
}

// String returns a human-readable representation of the stats
func (s ArtifactStats) String() string {
	return fmt.Sprintf(
		"Artifacts: %d total, %s total size, %d sessions",
		s.Total,
		formatBytes(s.TotalSize),
		len(s.BySession),
	)
}

// generateArtifactID generates a unique ID for an artifact based on its content
func generateArtifactID(content string) string {
	hash := sha256.Sum256([]byte(content))
	return "artifact_" + hex.EncodeToString(hash[:8])
}

// ArtifactFilter defines a function type for filtering artifacts
type ArtifactFilter func(*Artifact) bool

// FilterArtifacts returns artifacts that match the given filter
func FilterArtifacts(artifacts []*Artifact, filter ArtifactFilter) []*Artifact {
	var result []*Artifact
	for _, artifact := range artifacts {
		if filter(artifact) {
			result = append(result, artifact)
		}
	}
	return result
}

// Common artifact filters

// FilterArtifactsByType returns a filter that matches artifacts of the given type
func FilterArtifactsByType(artifactType ArtifactType) ArtifactFilter {
	return func(a *Artifact) bool {
		return a.Type == artifactType
	}
}

// FilterArtifactsByLanguage returns a filter that matches artifacts with the given language
func FilterArtifactsByLanguage(language string) ArtifactFilter {
	return func(a *Artifact) bool {
		return a.Language == language
	}
}

// FilterArtifactsByMinSize returns a filter that matches artifacts above a size threshold
func FilterArtifactsByMinSize(minSize int64) ArtifactFilter {
	return func(a *Artifact) bool {
		return a.Size >= minSize
	}
}

// FilterArtifactsSince returns a filter that matches artifacts created after a timestamp
func FilterArtifactsSince(since time.Time) ArtifactFilter {
	return func(a *Artifact) bool {
		return a.Created.After(since)
	}
}

// Helper methods for Artifact

// WithMetadata adds metadata to an artifact (builder pattern)
func (a *Artifact) WithMetadata(key string, value any) *Artifact {
	if a.Metadata == nil {
		a.Metadata = make(map[string]any)
	}
	a.Metadata[key] = value
	return a
}

// WithLanguage sets the programming language (builder pattern)
func (a *Artifact) WithLanguage(language string) *Artifact {
	a.Language = language
	return a
}

// WithFilename sets the suggested filename (builder pattern)
func (a *Artifact) WithFilename(filename string) *Artifact {
	a.Filename = filename
	return a
}

// WithDescription sets the description (builder pattern)
func (a *Artifact) WithDescription(description string) *Artifact {
	a.Description = description
	return a
}

// WithMIME sets the MIME type (builder pattern)
func (a *Artifact) WithMIME(mime string) *Artifact {
	a.MIME = mime
	return a
}

// ToMessage converts an artifact to an AgentMessage
func (a *Artifact) ToMessage() *AgentMessage {
	return &AgentMessage{
		Role:         "assistant",
		Content:      a.Content,
		Type:         MessageTypeArtifact,
		ArtifactID:   a.ID,
		ArtifactType: a.Type,
		ArtifactMIME: a.MIME,
		ArtifactSize: a.Size,
		SessionID:    a.SessionID,
		Timestamp:    a.Created,
		Metadata:     a.Metadata,
	}
}

// Clone creates a deep copy of the artifact
func (a *Artifact) Clone() *Artifact {
	clone := *a

	if a.Metadata != nil {
		clone.Metadata = make(map[string]any, len(a.Metadata))
		for k, v := range a.Metadata {
			clone.Metadata[k] = v
		}
	}

	return &clone
}
