// PicoClaw - Ultra-lightweight personal AI agent
// License: MIT
//
// Copyright (c) 2026 PicoClaw contributors

package agent

import (
	"context"
	"fmt"
	"time"

	"github.com/sipeed/picoclaw/pkg/logger"
	"github.com/sipeed/picoclaw/pkg/providers"
)

// RunStreamAgentLoop runs a streaming LLM agent loop for voice input.
// Text tokens are delivered via onToken as they are generated by the LLM.
// Tool calls are executed transparently between iterations; the loop
// re-prompts with results and continues until no more tool calls are issued
// or MaxIterations is reached.
// The full exchange is persisted to session memory on completion.
func (al *AgentLoop) RunStreamAgentLoop(
	ctx context.Context,
	sessionKey, userText, channel, chatID string,
	onToken func(string),
) error {
	agentInst := al.registry.GetDefaultAgent()
	if agentInst == nil {
		return fmt.Errorf("no default agent available")
	}

	sp, ok := agentInst.Provider.(providers.StreamingProvider)
	if !ok {
		return fmt.Errorf("provider %T does not implement StreamingProvider", agentInst.Provider)
	}

	start := time.Now()

	history := agentInst.Sessions.GetHistory(sessionKey)
	summary := agentInst.Sessions.GetSummary(sessionKey)
	messages := agentInst.ContextBuilder.BuildMessages(
		history, summary, userText, nil, channel, chatID,
	)

	agentInst.Sessions.AddMessage(sessionKey, "user", userText)

	llmOpts := map[string]any{
		"max_tokens":       agentInst.MaxTokens,
		"temperature":      agentInst.Temperature,
		"prompt_cache_key": agentInst.ID,
	}

	var finalContent string
	for iteration := 0; iteration < agentInst.MaxIterations; iteration++ {
		toolDefs := agentInst.Tools.ToProviderDefs()

		// Only stream tokens on the first (user-facing) iteration.
		// Subsequent iterations are tool-follow-up calls; no need to stream them.
		var tokenCb func(string)
		if iteration == 0 {
			tokenCb = onToken
		}

		resp, err := sp.ChatStream(ctx, messages, toolDefs, agentInst.Model, llmOpts, tokenCb)
		if err != nil {
			return fmt.Errorf("stream error (iteration %d): %w", iteration+1, err)
		}
		finalContent = resp.Content

		if len(resp.ToolCalls) == 0 {
			break
		}

		// Normalize tool calls so Name/Arguments map are always populated.
		normalizedCalls := make([]providers.ToolCall, 0, len(resp.ToolCalls))
		for _, tc := range resp.ToolCalls {
			normalizedCalls = append(normalizedCalls, providers.NormalizeToolCall(tc))
		}

		// Append assistant message with tool calls.
		assistantMsg := providers.Message{
			Role:    "assistant",
			Content: resp.Content,
		}
		for _, tc := range normalizedCalls {
			assistantMsg.ToolCalls = append(assistantMsg.ToolCalls, tc)
		}
		messages = append(messages, assistantMsg)

		// Execute each tool and add results to context.
		for _, tc := range normalizedCalls {
			result := agentInst.Tools.Execute(ctx, tc.Name, tc.Arguments)
			messages = agentInst.ContextBuilder.AddToolResult(
				messages, tc.ID, tc.Name, result.ForLLM,
			)
			logger.DebugCF("voice-stream", "Tool executed",
				map[string]any{"tool": tc.Name, "result_len": len(result.ForLLM)})
		}
	}

	agentInst.Sessions.AddMessage(sessionKey, "assistant", finalContent)
	if err := agentInst.Sessions.Save(sessionKey); err != nil {
		logger.WarnCF("voice-stream", "Failed to save session",
			map[string]any{"session_key": sessionKey, "error": err.Error()})
	}

	logger.InfoCF("voice-stream", "Stream completed",
		map[string]any{
			"session_key": sessionKey,
			"latency_ms":  time.Since(start).Milliseconds(),
			"content_len": len(finalContent),
		})

	return nil
}
